In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/
MyDrive/try/project/Copy of complaints.csv')

/tmp/ipython-input-2-3274547353.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/try/project/Copy of complaints.csv')

In [12]:
#number of nulls each column
df.isnull().sum()

Date received                        0
Product                              0
Sub-product                     235290
Issue                                0
Sub-issue                       839516
Consumer complaint narrative         0
Company public response              0
Company                              0
State                                0
ZIP code                             0
Consumer consent provided?           0
Submitted via                        0
Date sent to company                 0
Company response to consumer         0
Timely response?                     0
Consumer disputed?                   0
Complaint ID                         0
dtype: int64

In [5]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,Experian Information Solutions Inc.,FL,32092,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195687
1,2025-06-20,Debt collection,Telecommunications debt,Attempts to collect debt not owed,Debt is not yours,NaN,Company can't verify or dispute the facts in t...,"Eastern Account Systems of Connecticut, Inc.",FL,342XX,NaN,NaN,Web,2025-06-20,Closed with explanation,Yes,NaN,14195688
2,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",AZ,85225,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195689
3,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,NaN,Experian Information Solutions Inc.,AZ,85225,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195690
4,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account status incorrect,NaN,NaN,Experian Information Solutions Inc.,IL,60628,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195692

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9609797 entries, 0 to 9609796
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Date received                 object
 1   Product                       object
 2   Sub-product                   object
 3   Issue                         object
 4   Sub-issue                     object
 5   Consumer complaint narrative  object
 6   Company public response       object
 7   Company                       object
 8   State                         object
 9   ZIP code                      object
 10  Tags                          object
 11  Consumer consent provided?    object
 12  Submitted via                 object
 13  Date sent to company          object
 14  Company response to consumer  object
 15  Timely response?              object
 16  Consumer disputed?            object
 17  Complaint ID                  int64
dtypes: int64(1), object(17)
memory usage: 1.3+ GB

In [7]:
# prompt: list columns with more than 70 % nan

nan_counts = df.isnull().sum()
nan_percentage = nan_counts / len(df)
columns_to_drop = nan_percentage[nan_percentage > 0.1].index.tolist()
columns_to_drop

['Consumer complaint narrative',
 'Company public response',
 'Tags',
 'Consumer consent provided?',
 'Consumer disputed?']

Consumer disputed filled null values  with "No"

droped Tags column since it is more than 70 % nan and it is not essenscial

In [8]:
# prompt: drop row with null "Issue"

df.dropna(subset=["Issue"], inplace=True)

In [13]:
df = df.drop(columns=['Tags'])
df = df.drop(columns=['Sub-issue'])
df = df.drop(columns=['Sub-product'])

In [10]:
df['Consumer disputed?'] = df['Consumer disputed?'].fillna('No')
df['Consumer consent provided?'] = df['Consumer consent provided?'].fillna('No consent provided')
df['Company public response'] = df['Company public response'].fillna('No public response')
df['State'] = df['State'].fillna('unknown')
df['ZIP code'] = df['ZIP code'].fillna('unknown')
df['Company response to consumer'] = df['Company response to consumer'].fillna('No response')

for null of Consumer complaint narrative Imputed with Issue + Sub-issue

In [11]:
df['Consumer complaint narrative'] = df['Consumer complaint narrative'].fillna(
    df['Issue']
)